const mongoose = require("mongoose");

const systemMessageSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    datasetName: {
      type: String,
      required: true,
    },
    datasetId: {
      type: String,
    },
    type: {
      type: String,
      enum: ["error", "success", "info"],
      default: "info",
    },
    title: {
      type: String,
      required: true,
    },
    content: {
      type: String,
      required: true,
    },
    llmCode: {
      type: String, // Optional: The code generated by Gemini to auto-heal
    },
    traceback: {
      type: String, // Optional: The stack trace that triggered the healing
    },
    aiAdvice: {
      type: String, // Optional: Specialized ML model advice from Gemini
    }
  },
  { timestamps: true }
);

module.exports = mongoose.model("SystemMessage", systemMessageSchema);
